cumplo_challenge/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('site-admin/', admin.site.urls),
    path('', include('web_service.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

web_service/urls.py
from django.urls import path
from. import views

app_name = 'web_service'

urlpatterns = [
    path('', views.home, name='home'),
]

web_service/models.py
from django.db import models

# Create your models here.

web_service/views.py
"""
@author: Jorge Salazar
@since: 14 Feb 2021
@TODO: This script request information from Banxico web service
       to get the UDIS and Dollar value requested from a time
        period and shows with the following requirements.

        UDIS
        - Print the UDIS's value in Pesos foreach day of the
        defined time period.
        - Print the average, max value and min value of the UDIS in
        the time period.
        - Draw a graph with the UDIS's values by the days in the
        time period.

        DOLLAR
        - Print the Dollar's value in Pesos foreach day of the
        defined time period.
        - Print the average, max value and min value of the Dollar in
        the time period.
        - Draw a graph with the Dollar's values by the days in the
        time period.
"""

from django.shortcuts import get_object_or_404, render
import requests
import json


class RequestUtil:

    def __init__(self):
        self.url = 'https://www.banxico.org.mx/SieAPIRest/service/v1/series/'
        self.headers = {
            'Bmx-Token': 'd7c3482635131008a0bd73ef4aaa1bdfcfdebeccee800c932175434a5c52ed9a'
        }


    def build_url(self, idSerie, fechaIni=None, fechaFin=None):
        """
        This funciton builds the url to sent request
        :param idSerie: the Id of the Banxico catalog
        :type idSerie: str
        :param fechaIni: The period start to consult in format YYYY-MM-DD
        :type fechaIni: str
        :param fechaFin: The period end to consult in format YYYY-MM-DD
        :type fechaFin: str
        :returns: The built url to send to requests function
        :rtype: str
        """
        if (fechaIni or fechaFin) and not(fechaIni == '' or fechaFin == ''):
            params = '%s/datos/%s/%s' % (''.join(idSerie), fechaIni, fechaFin)
        else:
            raise AttributeError("Please insert a valid time period")
        print(self.url + params)
        return self.url + params



    def send_request(self, url):
        """
        This function send a request to HTTP server.
        :param url: the built url to request data
        :type url: str
        :param headers: the headers of the request
        :type headers: str
        :returns: the content of the request
        :rtype: str
        """
        response    = requests.get(url, headers=self.headers)
        status_code = response.status_code

        if response.status_code == 200:
            content = response.content
            return content
        raise ValueError('The request finished with code %s' % status_code)


    def parse_content(self, content):
        """
        This function parses the request content into a dictionary structure
        to show the data in the templates.
        :param content: the returned request content
        :type content: json
        :returns: Data structured into a dictionary
        :rtype: dictionary
        """
        content = json.loads(content)
        parsed_content_list = []

        for serie in content['bmx']['series']:
            parsed_content = {}
            parsed_content['title'] = serie['titulo']
            parsed_content['data'] = serie['datos']

            data = [float(dato['dato']) for dato in serie['datos']]

            parsed_content['average'] = round(sum(data) / len(data), 6)
            parsed_content['min'] = min(data)
            parsed_content['max'] = max(data)

            parsed_content_list.append(parsed_content)

        return parsed_content_list


###
# Views functions to render templates
###
def home(request):
    """
    This function builds the index page using the index.html template
    from web_service django application.
    """
    request_content = None
    error_message = None
    if request.method == 'POST':
        # Request data to Banxico web service
        banx_req_obj = RequestUtil()
        try:
            request_url = banx_req_obj.build_url(
                request.POST['idSerie'],
                request.POST['fechaIni'],
                request.POST['fechaFin']
            )
            request_content = banx_req_obj.send_request(request_url)
            request_content = banx_req_obj.parse_content(request_content)
        except Exception as e:
            error_message = str(e)
    context = {
        'content_list': request_content,
        'error_message': error_message,
    }
    return render(request, 'web_service/index.html', context)

web_service/templates/web_service/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    {% block head %}
    {% endblock %}
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <div class="container">
        {% block body %}
        {% endblock %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
    {% block body_bottom %}
    {% endblock %}
</body>
</html>

web_service/templates/web_service/index.html
{% extends "web_service/base.html"%}
{% load static %}
{% block head %}
    <link href="{% static 'web_service/css/index.css' %}" rel="stylesheet"/>
    <link href="{% static 'web_service/css/Chart.min.css' %}" rel="stylesheet"/>
    <script src="{% static 'web_service/js/Chart.js' %}"></script>
{% endblock %}
{% block title %}
    Cumplo Challenge
{% endblock %}
{% block body %}
    <h2 class="main-header">Cumplo Challenge</h2>
    <form action="{% url 'web_service:home' %}" method="post">
        {% csrf_token %}
        {% if error_message %}
            <div class="row"><div class="col-7 error"><strong>{{ error_message }}</strong></div></div>
        {% endif %}
        <div class="row form">
            <div class="col-auto">
                <label for="idSerie" class="form-label">Serie</label>
                <select name="idSerie" id="idSerie" class="form-select">
                    <option value="SP68257">UDIS</option>
                    <option value="SF43718">DOLLAR</option>
                    <option value="SF43783,SF43878,SF111916">TIIE</option>
                </select>
            </div>
            <div class="col-auto">
                <label for="fechaIni" class="form-label">Start Date</label>
                <input name="fechaIni" id="fechaIni" type="date" class="form-control"/>
            </div>
            <div class="col-auto">
                <label for="fechaFin" class="form-label">End Date</label>
                <input name="fechaFin" id="fechaFin" type="date" class="form-control"/>
            </div>
            <div class="col-auto"><input type="submit" value="Consult" class="btn btn-success btn-submit"/></div>
        </div>
    </form>
    {% if content_list %}
        {% for content in content_list %}
            <h4 class="title">{{ content.title }}</h4>
            <canvas id="canvas-{{ forloop.counter }}" style="display: block; width:80vw; height:40vh;" class="chartjs-render-monitor"></canvas>
            <div class="container">
                <table class="table table-responsive table-vals">
                    <thead class="table-success">
                        <tr>
                            <th>Average</th>
                            <th>Max Value</th>
                            <th>Min Value</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>{{ content.average }}</td>
                            <td>{{ content.max }}</td>
                            <td>{{ content.min }}</td>
                        </tr>
                    </tbody>
                </table>
                <table class="table table-hover table-responsive table-vals">
                    <thead class="table-primary">
                        <tr>
                            <th>Date</th>
                            <th>Value</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for row in content.data %}
                            <tr>
                                <td>{{ row.fecha }}</td>
                                <td>{{ row.dato }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <script>
                var config = {
                    type: 'line',
                    data: {
                        labels: [{% for data in content.data %}'{{ data.fecha }}',{% endfor %}],
                        datasets: [{
                            label: '',
                            backgroundColor: 'rgb(75, 192, 192)',
                            borderColor: 'rgb(75, 192, 192)',
                            data: [{% for data in content.data %}'{{ data.dato }}',{% endfor %}],
                            fill: false,
                        }]
                    },
                    options: {
                        responsive: true,
                        tooltips: {
                            mode: 'index',
                            intersect: false,
                        },
                        hover: {
                            mode: 'nearest',
                            intersect: true
                        },
                        scales: {
                            xAxes: [{
                                display: true,
                                scaleLabel: {
                                    display: true,
                                    labelString: 'Date'
                                }
                            }],
                            yAxes: [{
                                display: true,
                                scaleLabel: {
                                    display: true,
                                    labelString: 'Value'
                                }
                            }]
                        }
                    }
                };
                var ctx = document.getElementById('canvas-{{ forloop.counter }}').getContext('2d');
                window.myLine = new Chart(ctx, config);
            </script>
        {% endfor %}
    {% endif %}
{% endblock %}
{% block body_bottom %}

{% endblock %}